_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.13
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
BATCH_SIZE:
    value: 16
EPOCHS:
    value: 10
LEARNING_RATE:
    value: 0.0001
data_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/CoT_data_process/CoT_data
dataset:
    value: twitter2017
gradient_accumulation_steps:
    value: 4
img_feat_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/img_data
max_seq_len:
    value: 128
output_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/results/A2II-CoT-twitter2017/24
output_log_name:
    value: log
output_model_name:
    value: pytorch_model
run_name:
    value: pytorch_model
seed:
    value: 24
warmup_proportion:
    value: 0.1
