_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.13
            "5": 0.18.6
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
BATCH_SIZE:
    value: 8
EPOCHS:
    value: 1
LEARNING_RATE:
    value: 5e-05
data_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/img_data
dataset:
    value: twitter2015
gradient_accumulation_steps:
    value: 4
img_feat_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/img_data
max_seq_length:
    value: 150
output_dir:
    value: /data/lzy1211/code/A2II/instructBLIP/results/twitter2015-sweep/
output_log_name:
    value: log
output_model_name:
    value: pytorch_model
run_name:
    value: pytorch_model
seed:
    value: 42
warmup_proportion:
    value: 0.1
